[package]
name = "voxel-rs"
version = "0.1.0"
# TODO: Add email
authors = ["Technici4n"]


[dependencies]
gfx = "*"
gfx_device_gl = "*"
glutin = "*"
gfx_window_glutin = "*"
image = "*"
texture_packer = "*"
cgmath = "*"
noise = "*"
rand = "*"
serde = "*"
serde_derive = "*"
toml = "*"
cobalt = "*"
bincode = "*"
net2 = "*"

[patch.crates-io]
cobalt = { git = 'https://github.com/Technici4n/cobalt-rs' }
